---
replicaCount: 1
command: ["/bin/syphon"]
args:
  - "--config"
  - "/etc/syphon/config.toml"
image:
  repository: butlerx/syphon
  pullPolicy: IfNotPresent

config: {}
service:
  type: ClusterIP
  ports:
    udp: 2003
    tcp: 2003
    prometheus: 2006

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
