apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "syphon.fullname" . }}
  labels: {{- include "syphon.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "syphon.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "syphon.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ default .Values.image.tag .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: tcp
              containerPort: 2003
              protocol: TCP
            - name: udp
              containerPort: 2003
              protocol: UDP
            - name: prometheus
              containerPort: 2006
              protocol: TCP
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.command }}
          command: {{- toYaml . | trim | nindent 12 }}
          {{- end }}
          {{- with .Values.args }}
          args: {{- toYaml . | trim | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: configs
              mountPath: /etc/syphon/config.toml
              subPath: config.toml
              readOnly: true
      volumes:
        - name: configs
          configMap: {{- include "chart.configMapName" $ | nindent 4 }}
    {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
    {{- end }}
