apiVersion: v1
kind: Service
metadata:
  name: {{ include "syphon.fullname" . }}
  labels: {{- include "syphon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.prometheus }}
      targetPort: prometheus
      protocol: TCP
      name: prometheus
    - port: {{ .Values.service.ports.tcp }}
      targetPort: tcp
      protocol: TCP
      name: tcp
    - port: {{ .Values.service.ports.udp }}
      targetPort: udp
      protocol: UDP
      name: udp
  selector: {{- include "syphon.selectorLabels" . | nindent 4 }}
